package apply

import (
	"strings"
	"testing"

	"github.com/crmne/hyprmoncfg/internal/hypr"
	"github.com/crmne/hyprmoncfg/internal/profile"
)

func TestCommandsForProfile(t *testing.T) {
	mon := hypr.Monitor{Name: "DP-1", Make: "Dell", Model: "U2720Q", Serial: "A1"}
	p := profile.New("desk", []profile.OutputConfig{{
		Key:       mon.HardwareKey(),
		Name:      "DP-1",
		Enabled:   true,
		Width:     2560,
		Height:    1440,
		Refresh:   144,
		X:         0,
		Y:         0,
		Scale:     1,
		Transform: 0,
	}})

	cmds, err := CommandsForProfile(p, []hypr.Monitor{mon})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cmds) != 1 {
		t.Fatalf("expected 1 command, got %d", len(cmds))
	}
	if !strings.Contains(cmds[0], "DP-1,2560x1440@144") {
		t.Fatalf("unexpected command: %s", cmds[0])
	}
}

func TestCommandsForProfileDisable(t *testing.T) {
	mon := hypr.Monitor{Name: "HDMI-A-1", Make: "LG", Model: "27GP850", Serial: "B2"}
	p := profile.New("dock", []profile.OutputConfig{{
		Key:     mon.HardwareKey(),
		Name:    mon.Name,
		Enabled: false,
	}})

	cmds, err := CommandsForProfile(p, []hypr.Monitor{mon})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cmds) != 1 || cmds[0] != "HDMI-A-1,disable" {
		t.Fatalf("unexpected disable command: %+v", cmds)
	}
}

func TestKeywordifyMonitorCommandsLeavesWorkspaceAndDispatchCommandsUntouched(t *testing.T) {
	commands := []string{
		"DP-1,2560x1440@144,0x0,1",
		"keyword workspace 1, monitor:desc:Dell U2720Q, default:true",
		"dispatch moveworkspacetomonitor 1 DP-1",
	}

	got := keywordifyMonitorCommands(commands)
	want := []string{
		"keyword monitor DP-1,2560x1440@144,0x0,1",
		"keyword workspace 1, monitor:desc:Dell U2720Q, default:true",
		"dispatch moveworkspacetomonitor 1 DP-1",
	}

	if len(got) != len(want) {
		t.Fatalf("expected %d commands, got %d", len(want), len(got))
	}
	for idx := range want {
		if got[idx] != want[idx] {
			t.Fatalf("command %d mismatch: got %q want %q", idx, got[idx], want[idx])
		}
	}
}

func TestValidateLayoutRejectsOverlaps(t *testing.T) {
	outputs := []profile.OutputConfig{
		{
			Key:     "left",
			Name:    "DP-1",
			Enabled: true,
			Width:   2560,
			Height:  1440,
			X:       0,
			Y:       0,
			Scale:   1,
		},
		{
			Key:     "right",
			Name:    "eDP-1",
			Enabled: true,
			Width:   1920,
			Height:  1200,
			X:       2500,
			Y:       0,
			Scale:   1,
		},
	}

	if err := ValidateLayout(outputs); err == nil {
		t.Fatal("expected overlap validation error")
	}
}

func TestRenderHyprlandConfigUsesMonitorV2WithWorkspaceRules(t *testing.T) {
	monitors := []hypr.Monitor{
		{Name: "DP-1", Description: "Microstep MPG321UR-QD", Make: "Microstep", Model: "MPG321UR-QD"},
	}
	p := profile.New("desk", []profile.OutputConfig{{
		Key:       monitors[0].HardwareKey(),
		Name:      "DP-1",
		Enabled:   true,
		Width:     3840,
		Height:    2160,
		Refresh:   143.99,
		X:         3720,
		Y:         951,
		Scale:     1.33,
		VRR:       1,
		Transform: 0,
	}})
	p.Workspaces = profile.WorkspaceSettings{
		Enabled:       true,
		Strategy:      profile.WorkspaceStrategySequential,
		MaxWorkspaces: 3,
		GroupSize:     3,
		MonitorOrder:  []string{monitors[0].HardwareKey()},
	}

	rendered, err := RenderHyprlandConfig(p, monitors, true)
	if err != nil {
		t.Fatalf("unexpected render error: %v", err)
	}

	for _, want := range []string{
		"# Generated by hyprmoncfg",
		"monitorv2 {",
		"output = desc:Microstep MPG321UR-QD",
		"position = 3720x951",
		"scale = 1.33",
		"vrr = 1",
		"workspace = 1, monitor:desc:Microstep MPG321UR-QD, default:true, persistent:true",
	} {
		if !strings.Contains(rendered, want) {
			t.Fatalf("rendered config missing %q:\n%s", want, rendered)
		}
	}
}

func TestCommandsForProfileMirror(t *testing.T) {
	primary := hypr.Monitor{Name: "DP-1", Make: "Dell", Model: "U2720Q", Serial: "A1"}
	secondary := hypr.Monitor{Name: "HDMI-A-1", Make: "LG", Model: "27GP850", Serial: "B2"}
	p := profile.New("mirror", []profile.OutputConfig{
		{
			Key:     primary.HardwareKey(),
			Name:    "DP-1",
			Enabled: true,
			Width:   2560,
			Height:  1440,
			Refresh: 144,
			Scale:   1,
		},
		{
			Key:      secondary.HardwareKey(),
			Name:     "HDMI-A-1",
			Enabled:  true,
			MirrorOf: primary.HardwareKey(),
		},
	})

	cmds, err := CommandsForProfile(p, []hypr.Monitor{primary, secondary})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(cmds) != 2 {
		t.Fatalf("expected 2 commands, got %d: %v", len(cmds), cmds)
	}
	if !strings.Contains(cmds[1], "mirror,DP-1") {
		t.Fatalf("expected mirror command targeting DP-1, got: %s", cmds[1])
	}
}

func TestRenderHyprlandConfigMirrorV1(t *testing.T) {
	primary := hypr.Monitor{Name: "DP-1", Description: "Dell U2720Q", Make: "Dell", Model: "U2720Q", Serial: "A1"}
	secondary := hypr.Monitor{Name: "HDMI-A-1", Description: "LG 27GP850", Make: "LG", Model: "27GP850", Serial: "B2"}
	p := profile.New("mirror", []profile.OutputConfig{
		{
			Key:     primary.HardwareKey(),
			Name:    "DP-1",
			Enabled: true,
			Width:   2560,
			Height:  1440,
			Refresh: 144,
			Scale:   1,
		},
		{
			Key:      secondary.HardwareKey(),
			Name:     "HDMI-A-1",
			Enabled:  true,
			MirrorOf: primary.HardwareKey(),
		},
	})

	rendered, err := RenderHyprlandConfig(p, []hypr.Monitor{primary, secondary}, false)
	if err != nil {
		t.Fatalf("unexpected render error: %v", err)
	}
	if !strings.Contains(rendered, "mirror,desc:Dell U2720Q") {
		t.Fatalf("expected v1 mirror line with desc: selector, got:\n%s", rendered)
	}
}

func TestRenderHyprlandConfigMirrorV2(t *testing.T) {
	primary := hypr.Monitor{Name: "DP-1", Description: "Dell U2720Q", Make: "Dell", Model: "U2720Q", Serial: "A1"}
	secondary := hypr.Monitor{Name: "HDMI-A-1", Description: "LG 27GP850", Make: "LG", Model: "27GP850", Serial: "B2"}
	p := profile.New("mirror", []profile.OutputConfig{
		{
			Key:     primary.HardwareKey(),
			Name:    "DP-1",
			Enabled: true,
			Width:   2560,
			Height:  1440,
			Refresh: 144,
			Scale:   1,
		},
		{
			Key:      secondary.HardwareKey(),
			Name:     "HDMI-A-1",
			Enabled:  true,
			MirrorOf: primary.HardwareKey(),
		},
	})

	rendered, err := RenderHyprlandConfig(p, []hypr.Monitor{primary, secondary}, true)
	if err != nil {
		t.Fatalf("unexpected render error: %v", err)
	}
	if !strings.Contains(rendered, "mirror = desc:Dell U2720Q") {
		t.Fatalf("expected v2 mirror block, got:\n%s", rendered)
	}
	// The mirror block should contain only output + mirror, not mode/position/scale.
	mirrorIdx := strings.Index(rendered, "desc:LG 27GP850")
	if mirrorIdx < 0 {
		t.Fatalf("mirror monitor block not found in:\n%s", rendered)
	}
	mirrorBlock := rendered[mirrorIdx:]
	endIdx := strings.Index(mirrorBlock, "}")
	if endIdx >= 0 {
		mirrorBlock = mirrorBlock[:endIdx]
	}
	for _, forbidden := range []string{"position", "mode", "scale"} {
		if strings.Contains(mirrorBlock, forbidden) {
			t.Fatalf("mirror v2 block should not contain %q, got:\n%s", forbidden, rendered)
		}
	}
}

func TestValidateLayoutSkipsMirroredMonitors(t *testing.T) {
	outputs := []profile.OutputConfig{
		{
			Key:     "primary",
			Name:    "DP-1",
			Enabled: true,
			Width:   2560,
			Height:  1440,
			X:       0,
			Y:       0,
			Scale:   1,
		},
		{
			Key:      "secondary",
			Name:     "HDMI-A-1",
			Enabled:  true,
			Width:    2560,
			Height:   1440,
			X:        0,
			Y:        0,
			Scale:    1,
			MirrorOf: "primary",
		},
	}

	if err := ValidateLayout(outputs); err != nil {
		t.Fatalf("mirrored monitor should not trigger overlap: %v", err)
	}
}

func TestSnapshotCommandsMirror(t *testing.T) {
	monitors := []hypr.Monitor{
		{Name: "DP-1", Width: 2560, Height: 1440, RefreshRate: 144, Scale: 1},
		{Name: "HDMI-A-1", Width: 2560, Height: 1440, MirrorOf: "DP-1", Scale: 1},
	}

	cmds := SnapshotCommands(monitors)
	if len(cmds) != 2 {
		t.Fatalf("expected 2 commands, got %d: %v", len(cmds), cmds)
	}
	if !strings.Contains(cmds[1], "mirror,DP-1") {
		t.Fatalf("expected snapshot mirror command, got: %s", cmds[1])
	}
}
